# Generated by Django 3.1.3 on 2024-05-30 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallePedidos',
            fields=[
                ('det_pedido_id', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('nombre_producto', models.TextField(blank=True)),
                ('cantidad', models.TextField(blank=True)),
                ('precio_unitario', models.TextField(blank=True)),
                ('total', models.TextField(blank=True)),
                ('fecha_pedido', models.TextField(blank=True)),
                ('pedido_id', models.TextField(blank=True)),
                ('producto_id', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'detalle_pedidos',
            },
        ),
        migrations.CreateModel(
            name='HistorialPedidos',
            fields=[
                ('pedido_id', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('total', models.TextField(blank=True)),
                ('fecha_pedido', models.TextField(blank=True)),
                ('cliente_id', models.TextField(blank=True)),
                ('producto_id', models.TextField(blank=True)),
                ('pago_id', models.TextField(blank=True)),
                ('det_pedido_id', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'historial_pedidos',
            },
        ),
        migrations.CreateModel(
            name='MetodoPagos',
            fields=[
                ('metodo_pago', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('nombre', models.TextField(blank=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'metodo_pagos',
            },
        ),
        migrations.DeleteModel(
            name='detalle_pedidos',
        ),
        migrations.DeleteModel(
            name='historial_pedidos',
        ),
        migrations.DeleteModel(
            name='metodo_pagos',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='id',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='id',
        ),
        migrations.RemoveField(
            model_name='inventarios',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='id',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='id',
        ),
        migrations.RemoveField(
            model_name='proveedores',
            name='id',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='id',
        ),
        migrations.AlterField(
            model_name='admin',
            name='admin_id',
            field=models.TextField(blank=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='categoria_id',
            field=models.TextField(blank=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inventarios',
            name='inventario_id',
            field=models.TextField(blank=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='pago_id',
            field=models.TextField(blank=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productos',
            name='producto_id',
            field=models.TextField(blank=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='proveedor_id',
            field=models.TextField(blank=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='usuario_id',
            field=models.TextField(blank=True, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='admin',
            table='admin',
        ),
        migrations.AlterModelTable(
            name='categoria',
            table='categoria',
        ),
        migrations.AlterModelTable(
            name='inventarios',
            table='inventarios',
        ),
        migrations.AlterModelTable(
            name='pagos',
            table='pagos',
        ),
        migrations.AlterModelTable(
            name='productos',
            table='productos',
        ),
        migrations.AlterModelTable(
            name='proveedores',
            table='proveedores',
        ),
        migrations.AlterModelTable(
            name='usuarios',
            table='usuarios',
        ),
    ]
