# Generated by Django 5.0.6 on 2024-05-31 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_id', models.TextField(blank=True)),
                ('nombre_fk', models.TextField(blank=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('det_pedido_id', models.TextField(blank=True)),
                ('nombre', models.TextField(blank=True)),
                ('cantidad', models.TextField(blank=True)),
                ('precio', models.TextField(blank=True)),
                ('total', models.URLField()),
                ('fecha_pedido', models.TextField(blank=True)),
                ('pedido_id', models.TextField(blank=True)),
                ('producto_id', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialPedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido_id', models.TextField(blank=True)),
                ('total', models.TextField(blank=True)),
                ('fecha_pedido', models.TextField(blank=True)),
                ('cliente_id', models.TextField(blank=True)),
                ('producto_id', models.TextField(blank=True)),
                ('det_pedido_id', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventario_id', models.TextField(blank=True)),
                ('nombre', models.TextField(blank=True)),
                ('stock', models.TextField(blank=True)),
                ('fecha_entrada', models.TextField(blank=True)),
                ('producto_id', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_id', models.TextField(blank=True)),
                ('nombre', models.TextField(blank=True)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.TextField(blank=True)),
                ('url', models.URLField()),
                ('categoria_id', models.TextField(blank=True)),
                ('proveedor_id', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor_id', models.TextField(blank=True)),
                ('nombre', models.TextField(blank=True)),
                ('direccion', models.TextField(blank=True)),
                ('telefono', models.TextField(blank=True)),
            ],
        ),
    ]
