# Generated by Django 5.0.6 on 2024-06-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
