# Generated by Django 5.0.6 on 2024-06-07 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_alter_productos_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='cantidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
